name: Frontend CI/CD Build & Deploy to S3

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-deploy:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
        # Lägg till env här senare om ni behöver, tex VITE_API_BASE_URL
      - name: Deploy to AWS S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-north-1'
          SOURCE_DIR: 'dist'
